### ISSUE TITLE
DigiCert certificate not recognized

### ISSUE THREAD

**Issue by metbril** [jobisoft/EAS-4-TbSync#127]
## Your environment

TbSync version: 2.16
EAS-4-TbSync version: 1.16
Thunderbird version: 78.0.1

- [x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

Connect to server and access account

## Actual behavior
When trying to connect to the server, the server shows an error about certificates

## Steps to reproduce

- Add EAS account with details
    - username: `MCRZ\username` (dummy)
    - password: `password` (dummy)
    - server: `webmail.maasstadziekenhuis.nl`

The error suggests that the certificate (DigiCert root) is invalid, but when I browse to https://webmail.maasstadziekenhuis.nl and look at the certificate it appears to be valid.

I can access mail on a smartphone without issues with the same credentials. 

Debug log (checked for personal info) [debug.log](https://github.com/jobisoft/EAS-4-TbSync/files/4958489/debug.log)

**Comment by jobisoft** [comment]
Thunderbird has its own certificate store, independet from your browser. Why Thunderbird does not know the issuer of that cert is beyond me. Try to install it manually:

https://github.com/jobisoft/TbSync/wiki/How-to-use-TbSync-with-self-signed-or-otherwise-untrusted-certificates%3F

This talks about self signed cert but is valid for any cert not trusted by Thunderbird.
