### ISSUE TITLE
Can't login hotmail and 2 factor

### ISSUE THREAD

**Issue by pcause** [jobisoft/EAS-4-TbSync#130]
I am on TB 78 and was able to connect my O365 account.  When I try to set up hotmail it can't connect or keeps prompting from my password.  I try outlook.com outlook.live.com and the like.  I do have 2 factor enabled for my account and wonder if that is the problem.

**Comment by RobMahn** [comment]
Have you tried using an App password?

**Comment by jobisoft** [comment]
As I have understood, the EAS endpoint does not support hotmail accounts via 2FA.

**Comment by RobMahn** [comment]
Hi John,

The Hotmail account is not 2FA and was working before.  It just started 
prompting for a password suddenly.  It would not accept a validated 
cut/paste password.


I tried deleting the account and adding it back in to no avail.


My Outlook.com account is 2FA and works with an app password.  This 
account is still working.


Thank you,

Rob Mahn

314-616-1387

*From: *John Bieling<mailto:notifications@github.com>
*Sent: *Friday, October 16, 2020 7:07 AM
*To: *jobisoft/EAS-4-TbSync<mailto:EAS-4-TbSync@noreply.github.com>
*Cc: *Rob Mahn<mailto:Rob.Mahn@Outlook.com>; 
Comment<mailto:comment@noreply.github.com>
*Subject: *Re: [jobisoft/EAS-4-TbSync] Can't login hotmail and 2 factor 
(#130)

As I have understood, the EAS endpoint does not support hotmail accounts 
via 2FA.

—
You are receiving this because you commented.
Reply to this email directly, view it on 
GitHub<https://github.com/jobisoft/EAS-4-TbSync/issues/130#issuecomment-710005779>, 
or

**Comment by jobisoft** [comment]
sorry to hear that. is it possible to create an app specific password in the hotmail webinterface?
