### ISSUE TITLE
TbSync is quarantined in Outlook

### ISSUE THREAD

**Issue by aik** [jobisoft/EAS-4-TbSync#178]
Outlook via web shows a TbSync mobile device which is quaranteened.
TB 91.11, Linux Fedora 36, TbSync 3.0.2, the login and password are accepted, TbSync reports "OK" but does not load anything from that account, why quaranteened, where to poke it?

**Comment by jobisoft** [comment]
The error you see is due to an empty response from your server. Sometimes empty responses are ok, but TbSync still prints the error. It does not mean that something is broken. 

If your device is quarantined, this could of course be a reason, why the server is not sending anything back. If your Office 365 tenants has quarantined a mobile device, then your tenant admin should be able to release it. But this becomes whoodoo at some point. I do not know why it got quarantined. Sorry.
