### ISSUE TITLE
Feature request: add emails to the synchronization stack

### ISSUE THREAD

**Issue by darealShadow** [jobisoft/EAS-4-TbSync#239]
## Your environment

TbSync version: unknown currently
Thunderbird version: 115

Currently I am using Outlook but want to switch completely away from any Microsoft products. In Outlook it is possible to not only sync calendars and contacts but also e-mails. I would like to request the same functionality for tbsync so in addition to syncing calendar and contacts my emails would be synced as well.

Thank you very much.

**Comment by lyzgeorge** [comment]
some customized email server like CoreMail banned IMAP/POP3, also banned Exchange protocols. It only allows either CoreMail App or Exchange ActiveSync mobile clients. I'm now having trouble to use email on my Mac (calendar/contact works fine), please still consider adding mail functions to this plugin, thanks a lot!

**Comment by jobisoft** [comment]
> some customized email server like CoreMail banned IMAP/POP3, also banned Exchange protocols.

What policy is behind that? Why do they disallow 99% of currently used access methods (global market share)? 

Exchange ActiveSync is also an Exchange protocol, so why do they exclude that from the ban?

Try the OWL add-on, could be that they support ActiveSync.

I will close this, since there is nothing to add besides https://github.com/jobisoft/EAS-4-TbSync/issues/239#issuecomment-1697130874.
