### ISSUE TITLE
Contact’s Department and Company are inverted between Thunderbird and Outlook

### ISSUE THREAD

**Issue by JacquesBelge** [jobisoft/EAS-4-TbSync#255]
## Your environment

TbSync version: 4.7
Thunderbird version: 115.4.1

## Expected behavior
Synchronization of all the data of contacts between Thunderbird and Outlook.

## Actual behavior
The data Department and Company are inverted.

## Steps to reproduce
1.	Create a contact in Outlook, with Company, Department and Job Title.
2.	Synchronize in Thunderbird
3.	Open the contact there and notice the difference

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Fixed in the EAS provider v4.8.

Once you have it installed, it will continue to display it wrong. You first have to unselect the address book in the TbSync Account Manager and then re-select it. TbSync will then download it fresh and use the correct mapping.

You can drag the attached zip file into Thunderbirds Add-on Manager tab, to install and test v4.8 now already:
[EAS-4-TbSync.zip](https://github.com/jobisoft/EAS-4-TbSync/files/13537674/EAS-4-TbSync.zip)
