### ISSUE TITLE
Multi-factor authentication on O365

### ISSUE THREAD

**Issue by jonxs** [jobisoft/EAS-4-TbSync#45]
I wanted to use TbSync with an O365 business account. I use MFA/2FA on this via Azure MFA. I tried using an app password or my standard password (to await a second authorisation) but neither worked.

TbSync version: 0.7.22 
Thunderbird version: 60.4.0

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
To authenticate and allow TbSync to function

## Actual behavior
Unable to authenticate

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by here-abarany** [comment]
From what I understand the app password only works when using Azure MFA. When using third-party MFA (e.g. Duo) you cannot use an app password. TbSync (and/or Thunderbird core?) would need to implement Active Directory Authentication Library (ADAL) in order to support all the different MFA services that Office 365 supports.

[Modern Authentication](https://www.microsoft.com/en-us/microsoft-365/blog/2015/11/19/updated-office-365-modern-authentication-public-preview/)
[ADAL libraries](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries)

**Comment by runekaagaard** [comment]
I can confirm it works with a generated app password. It took about an hour after I made the app password for Microsoft to allow the connection.

**Comment by jobisoft** [comment]
The latest beta now has support for Office 365 OAuth support, which schould work with MFA.
https://github.com/jobisoft/EAS-4-TbSync/issues/87#issuecomment-553479268
