### ISSUE TITLE
Sync with Microsoft Office 365 - usual password does not work

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/EAS-4-TbSync#46]
This is not an issue but a way to circumvent a common problem when authenticating to Office 365.
Maybe this could be added to the wiki?
But on the other hand, this hint may be used to integrate the mentioned authentication into the EAS add-on, so this could be an improvement for it.

I saw several people having problems to sync their Office 365 calendar with Thunderbird (Lightning) calendar.
The instructions to set up an Exchange Active Sync are correct so far, but when it comes to the point where TbSync tries to connect to the server, it won't accept any password you provide.

**The solution for this is quite simple but not obvious at first sight:**

In case, nothing seems to work, the administrator of your Office 365 tenant maybe enabled Multi-Factor Authentication for all users. 

As Thunderbird and TbSync do not seem to support the way, this kind of Authentication works (forms-based or other old authentication methods vs. Modern Authentication aka Azure AD Authentication Library (ADAL) using OAuth based authentication) you simply cannot be authenticated by your "regular" password.

**All you have to do is to create a so called "App-Password" within the Office 365 portal an use that for TbSync instead of your "regular" login password. For doing so, I added the links to Microsoft's descriptions in english and german, which describe, how to do it.**

German:
https://support.office.com/de-de/article/erstellen-eines-app-kennworts-f%C3%BCr-office-365-3e7c860f-bda4-4441-a618-b53953ee1183

English:
https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183?omkt=en-US&ui=en-US&rs=en-US&ad=US

I hope this will help some people to successfully use TbSync and Thunderbird with Office 365.

With best regards, Harry.

**Comment by jobisoft** [comment]
I would like to inform you, that the latest beta of TbSync has OAUTH support!
https://github.com/jobisoft/EAS-4-TbSync/issues/87#issuecomment-553479268

Feedback is welcome.

**Comment by GaryT-NZ** [comment]
Our organisation has just implemented/enforced OAuth2 on our accounts at office365, and tbsync stopped working (asking for new password), even after I updated the main thunderbird email settings.
This issue was the only mention I could find of OAuth and Tbsync, and reading this made me wonder if I needed the Beta.
To make it explicit/clear, the latest version now definitely has OAuth support.
Am I correct that there's no way to tell tbsync to change the authorisation? I ended up deleting and re-adding my tbsync calendar and task list, and it now works fine.
I thought I would add a note in case anyone else comes looking here.

**Comment by icarus42** [comment]
I can confirm that removing and adding the account again successfully helped me switching from a password prompt to an OAuth signgin.

**Comment by burgsteiner** [comment]
OAUTH2 works fine for syncing emails with Thunderbird with our Office 365 accounts. Interestingly, TbSync needs additonal access permissions. After successfully authenticating the user, an additional popup says:

"Administrator permission required. To access resources in your organization, tbsync.jobisoft.de requires permission that only an administrator can grant. Ask an administrator to grant permission for this app so that you can use the app."

Why is this? Is this a bug or a feature?

**Comment by jobisoft** [comment]
TbSync has no access to your email access token and I do not think the request for the email access token included the permission to read your calendar and address books.

I have no idea why you need admin permission. Your company probably blacklisted 3rd party apps.
